### PR TITLE
Added a Hifi pool registry contract

### PR DESCRIPTION
**Pull request by scorpion9979**

### CODE REVIEW

**Comment by scorpion9979** [comment]
@paulrberg The first draft is ready for review. I'll get to work on the tests once we agree on the interface.

I'm thinking we should just diminish the factory's role and make it into a basic LP registry that's sole purpose is to keep track of LPs that are already deployed manually. That means, we would simply take out the `createPool(...)` method and rename the contract into `HifiPoolRegistry`.

**Comment by scorpion9979** [comment]
I've scoped down the factory and it's now a simple registry that keeps track of what AMM pools exist.

**Review by PaulRBerg — CHANGES_REQUESTED** [review]
Todos:

- [x] Import the `IHifiPool.sol` file instead of `HifiPool.sol` in the `HifiPoolRegistry.sol` contract.
- [x] Rebase from `main` and delete the `deploy-hifiPool.ts` file. It looks like you replaced the deployment for` HifiPool` with a deployment for the registry. We're now using [hifi-deployers](https://github.com/hifi-finance/hifi-deployers) for deployment purposes.
- [x] We don't need the `HifiPoolRegistry__NoTrackedPools` error. It's superfluous. Delete it.

Questions:

1. Why do we need both a `pools` array and a `poolIds` mapping? I think that the latter would suffice, where the `uint256` type would become a `boolean`. You could create the array in the subgraph directly.

**Comment by scorpion9979** [comment]
@paulrberg 
> Questions:
> 
> 1. Why do we need both a `pools` array and a `poolIds` mapping? I think that the latter would suffice, where the `uint256` type would become a `boolean`. You could create the array in the subgraph directly.

I thought we might want to have an on-chain list of all the pools. For now, I think a minimalist implementation would work just fine for our subgraph purposes. I'll proceed to replace the registry storage vars the following mapping:
```solidity
mapping(IHifiPool => bool) public override poolIsTracked;
```

**Pull request closed without merging**
